# Generated by Django 4.2.23 on 2025-08-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResumeUpload",
        ),
    ]
