# Generated by Django 4.2.23 on 2025-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_api", "0003_resumeupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
