# Generated by Django 5.2.3 on 2025-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_api", "0004_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="linkedin_id",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultant",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
