# Generated by Django 5.2.3 on 2025-08-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_api", "0005_consultant_linkedin_id_consultant_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserATSResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_text", models.TextField()),
                ("ats_score", models.FloatField()),
                ("mistakes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ats_results",
                        to="consultant_api.consultant",
                    ),
                ),
            ],
        ),
    ]
